name: Build APK and Create GitHub Release
on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build-and-release.yml
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21.0.2'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Prebuild
        run: npx expo prebuild
      - name: Install React Native cli
        run: npm i -D @react-native-community/cli
      - name: Build APK
        run: |
          cd android
          ./gradlew app:assembleRelease
