name: Build APK and Create GitHub Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  unit-tests:
    uses: zhenya-mamenko/my-pillbox/.github/workflows/jest.yml@main

  build:
    name: Install and build
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21.0.2'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;35.0.0"
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Prebuild
        run: |
          npx expo prebuild --platform android
          sed -i 's/signingConfig signingConfigs.debug/signingConfig null/g' android/app/build.gradle
      - name: Build APK
        run: |
          cd android
          ./gradlew app:assembleRelease --no-daemon
      - name: Sign APK
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > release.keystore
          $ANDROID_SDK_ROOT/build-tools/36.0.0/apksigner sign \
            --ks release.keystore \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --out my-travel-pillbox.apk \
            android/app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: my-travel-pillbox.apk
          token: ${{ secrets.RELEASE_TOKEN }}
          body: |
            This is a new release of the My Travel Pillbox app.
            It includes the latest features and bug fixes.
            Download the APK and install it on your Android device.
          draft: false
          prerelease: false
          make_latest: true
